services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apache_server_objet
    ports:
      - "8084:80"
    volumes:
      - ./site:/var/www/html
    networks:
      - mynetwork

  mysql:
    #platform: linux/x86_64  # Pour les macs
    image: mysql:9.0
    container_name: mysql_db_objet
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: trombinoscope
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_objet:/var/lib/mysql
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_objet
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8085:80"
    depends_on:
      - mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  db_objet:
